<?php
/*
*   Plugin Name: Darkify Util
*   Description: A utility plugin to add dark mode functionality to your WordPress site.
*   Version: 1.4.0
 */

// If this file is called directly, abort.
if (!defined('ABSPATH')) {
    exit;
}

define('DARKIFY_UTIL_FILE', __FILE__);
define('DARKIFY_UTIL_PATH', plugin_dir_path(__FILE__));
define('DARKIFY_UTIL_URL', plugin_dir_url(__FILE__));
define('DARKIFY_UTIL_VERSION', '1.4.0');


/**
 * Pick the built or the readable copy of one of this plugin's own assets.
 *
 * Production serves the `.min` build; `WP_DEBUG`, or the `darkify_dev_mode`
 * filter, serves the readable source instead — the same switch and the same
 * filter name Darkify and Darkify Pro already use, so one setting governs all
 * three plugins.
 *
 * The `file_exists()` check is the point of returning a path rather than a
 * bare `.min` suffix: these builds are generated by a separate step, and a
 * suffix appended blindly turns a missing build into a 404 — which, for the
 * head-loaded scripts here, means a feature silently not working on the live
 * site. A missing build falls back to the readable file instead.
 *
 * @param string $relative_path Path under the plugin root, e.g. 'assets/js/x.js'.
 * @return string Relative path to whichever copy should actually be served.
 */
function darkify_util_asset($relative_path)
{
    $dev = apply_filters('darkify_dev_mode', false) || (defined('WP_DEBUG') && WP_DEBUG);

    if (!$dev) {
        $min = preg_replace('/\.(css|js)$/', '.min.$1', $relative_path);

        if ($min !== $relative_path && file_exists(DARKIFY_UTIL_PATH . $min)) {
            return $min;
        }
    }

    return $relative_path;
}

// enqueue the plugin's CSS and JavaScript files
function darkify_enqueue_scripts()
{
    $darkify_style = darkify_util_asset('assets/css/darkify.css');
    wp_enqueue_style('darkify-util-style', DARKIFY_UTIL_URL . $darkify_style, array(), DARKIFY_UTIL_VERSION);

    // $darkify_custom = darkify_util_asset('assets/js/custom-script.js');
    // wp_enqueue_script('darkify-util-script', DARKIFY_UTIL_URL . $darkify_custom, array(), DARKIFY_UTIL_VERSION, true);

    /*
     * The "Submit your site" reveal on the showcase page.
     *
     * Loaded only where the button actually is: its anchor is saved into the
     * post content by Kadence, so a substring test finds the page without
     * hard-coding an ID or a slug, and picks up the pattern automatically if
     * it is reused elsewhere.
     *
     * In the HEAD, not the footer, unlike everything above it. The paired CSS
     * hides the form only under a class this script sets on <html>, so it has
     * to run before first paint or the form is visible for a moment and then
     * collapses. See assets/js/darkify-submit-toggle.js.
     */
    if (is_singular()) {
        $darkify_post = get_post();

        if ($darkify_post && false !== strpos($darkify_post->post_content, 'submit_your_site')) {
            $darkify_toggle = darkify_util_asset('assets/js/darkify-submit-toggle.js');
            wp_enqueue_script('darkify-util-submit-toggle', DARKIFY_UTIL_URL . $darkify_toggle, array(), DARKIFY_UTIL_VERSION, false);
        }

        /*
         * The captions beside the Image Controls and Video Controls switches,
         * which have to describe whichever mode is currently on. Same content
         * test as above, and in the footer rather than the head: this one only
         * rewrites text that is already on the page, so it has nothing to do
         * before the content it edits has been parsed.
         */
        $darkify_label_anchors = array('image_control_btn', 'video_control_btn', 'data-darkify-label-toggle');

        foreach ($darkify_label_anchors as $darkify_anchor) {
            if ($darkify_post && false !== strpos($darkify_post->post_content, $darkify_anchor)) {
                $darkify_labels = darkify_util_asset('assets/js/darkify-mode-labels.js');
                wp_enqueue_script('darkify-util-mode-labels', DARKIFY_UTIL_URL . $darkify_labels, array(), DARKIFY_UTIL_VERSION, true);
                break;
            }
        }
    }
}

add_action('wp_enqueue_scripts', 'darkify_enqueue_scripts');

/**
 * The preview shortcodes. Both render a sample site into an isolated frame and
 * run the real Darkify engine inside it — [darkify_demo] for the visitor to
 * play with, [darkify_hero_demo] flipping itself on a loop — front end, then
 * wp-admin.
 */
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-preview.php';
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-demo.php';
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-hero.php';

add_action('plugins_loaded', array('Darkify_Util_Demo', 'instance'));
add_action('plugins_loaded', array('Darkify_Util_Hero', 'instance'));

/**
 * The Changelog, Collection, AI Summarize, Social Share and Promo Banner blocks
 * (and their [darkify_changelog], [darkify_collection], [darkify_ai_summarize],
 * [darkify_social_share] and [darkify_promo_banner] shortcodes) moved to the
 * standalone Atelier Blocks plugin in 1.4.0, under the same block names, so
 * the pages using them are unchanged. That plugin must be active for them to
 * render.
 */

/**
 * The one-time migration off the third-party changelog block the Changelogs
 * page used to depend on (Tools → Darkify Changelog Import, and
 * `wp darkify-util changelog migrate`).
 *
 * It converts into the Atelier Blocks changelog block and parses with that
 * plugin's parser, so it is offered only while Atelier Blocks is active: a
 * migration into a block nothing renders would leave the page empty.
 */
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-changelog-migrator.php';

add_action('plugins_loaded', function () {
    if (class_exists('Atelier_Blocks_Changelog_Parser')) {
        Darkify_Util_Changelog_Migrator::instance();
    }
});

/**
 * SVG uploads.
 *
 * WordPress refuses the format because an SVG is a document that can carry
 * scripts. The format is enabled here and every uploaded file is rewritten from
 * an allowlist before it is stored — the two always travel together, and the
 * sanitiser is required first so the mime type can never be allowed without it.
 */
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-svg-sanitizer.php';
require_once DARKIFY_UTIL_PATH . 'includes/class-darkify-util-svg.php';

add_action('plugins_loaded', array('Darkify_Util_SVG', 'instance'));


/**
 * Output the Tawk.to live chat script in the site footer.
 * Runs on every page/post since wp_footer fires site-wide, regardless of active theme.
 */
function darkify_tawkto_script() {
	?>
	<!--Start of Tawk.to Script-->
	<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/6773aa4eaf5bfec1dbe50a49/1jb58pjtu';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
	</script>
	<!--End of Tawk.to Script-->
	<?php
}
add_action( 'wp_footer', 'darkify_tawkto_script' );